### ISSUE TITLE
[Suggestion] in game configuration and cloud height sync

### ISSUE THREAD

**Issue by Aces-and-Jacks** [DaFuqs/HeadInTheClouds#1]
Being able to edit the cloud height in-game using modmenu and maybe syncing cloud height with the settings that are already set in game before

**Comment by DaFuqs** [comment]
Overriding vanilla / modded dimension cloud height? Sure

**Comment by MagmaSlime123** [comment]
> Overriding vanilla / modded dimension cloud height? Sure

Please see the issue I opened.

**Comment by DaFuqs** [comment]
done.
