### ISSUE TITLE
Potential incompat with Create

### ISSUE THREAD

**Issue by SlayerTheChikken** [DaFuqs/HeadInTheClouds#3]
The game crashes during ponder

Fabric 1.19.2 
create-fabric-0.5.1-c-build.1160+mc1.19.2

[crash-2023-11-02_18.03.48-client.txt](https://github.com/DaFuqs/HeadInTheClouds/files/13260606/crash-2023-11-02_18.03.48-client.txt)
[crash-2023-11-03_00.17.32-client.txt](https://github.com/DaFuqs/HeadInTheClouds/files/13260607/crash-2023-11-03_00.17.32-client.txt)

**Comment by DaFuqs** [comment]
Fixed in 1.0.1 ✔️

**Comment by SlayerTheChikken** [comment]
Does the 1.0.1 version work for 1.19.2? Sorry to bother
