### ISSUE TITLE
Sinytra Connector Compat?

### ISSUE THREAD

**Issue by DaddySpin** [DaFuqs/HeadInTheClouds#4]
When your mod is loaded with sinytra connector it does absolutely nothing.

**Comment by DaFuqs** [comment]
Sinytra Connector aims to make Fabric mods run on Forge
If it doesn't work, there probably is nothing resonable I can do on my end to fix it (besides making a full-fledged forge port, I suppose)
So sorry, no, can't do. Maybe Sinytra Connector improves in the future and it suddenly starts work? Would be cool, but who knows.
