### ISSUE TITLE
Support for Better Clouds.

### ISSUE THREAD

**Issue by MagmaSlime123** [DaFuqs/HeadInTheClouds#5]
Title, see https://modrinth.com/mod/better-clouds.

The last commit was 7 months ago, please remove if dead.

**Comment by DaFuqs** [comment]
I'm afraid that one has to be handled by Better Clouds, should it come alive again somehow.
HeadInTheClouds queries the internal cloud height. If better clouds has ways to tweak visual cloud height, it should also reflect that in the worlds internals (also important for all other mods that need to know the cloud height for whatever reason they might have)
