### ISSUE TITLE
Add API for actual weather no matter the displayed weather (BetterClouds Compat)

### ISSUE THREAD

**Issue by SabrCat** [DaFuqs/HeadInTheClouds#6]
As I explained here: https://github.com/Qendolin/better-clouds/issues/81. I love the effect of head in the clouds, but I would like better clouds to preserve the cloud density caused by the rain below the clouds, even if the player is above the clouds. This would help mask the issue of rain under the clouds not being visible from above. 
I originally made this a feature request to better clouds, but they answered they can't do much as they do not know what the actual weather is. 
My idea for a solution to this would be to add an API to HeadInTheClouds that allows mods to poll for the actual weather, no matter which weather is being displayed. Though a multitude of other solutions would probably work too. 
I'd love to see the two mods work better together, so thanks in advance for giving this a thought!

**Comment by DaFuqs** [comment]
Sure, can do!

**Comment by SabrCat** [comment]
Awesome, great to hear! Let me know whenever this might be ready. Also, if at all possible I'd appreciate a 1.20.1 release as I'll be stuck there for another year or so until create fabric finally updates.

**Comment by DaFuqs** [comment]
Added via: https://github.com/DaFuqs/HeadInTheClouds/commit/9ed121462ee0e46fe4a3e3d2cc57b488bc4de128
