### ISSUE TITLE
"No GUI provider registered for 'java.util.Map ... Config.WorldCloudHeights'" error when ModMenu is also installed

### ISSUE THREAD

**Issue by DefinitelyNotFred** [DaFuqs/HeadInTheClouds#7]
Full error string:
[Thread-6/ERROR]:No GUI provider registered for
field 'public java.util.Map de.dafuqs.head_in_the_clouds.config.Config.WorldCloudHeights'!

Attempting to configure Head in the Clouds through Mod Menu just shows an empty page, game plays just fine otherwise. No error shows up if Mod Menu isn't installed. No other mods are installed.

Head in the Clouds 1.1.0
Mod Menu 7.2.2
Cloth Config 11.1.118

Log file in case you want to see the full context: [latest.log](https://github.com/user-attachments/files/16397917/latest.log)

**Comment by DaFuqs** [comment]
Oh, good catch! I will poke at it

**Comment by kkempfer** [comment]
Same issue on my end with a slightly different configuration. All these mods are updated to their latest versions.

Minecraft: 1.19.2
Mod Loader: Fabric 0.16.0
Fabric API: 0.77.0
Head in the Clouds: 1.0.0
Mod Menu: 4.2.0-beta.2
Cloth config: 8.3.115

```
[14:39:21] [Render thread/ERROR]: No GUI provider registered for field 'public java.util.Map de.dafuqs.head_in_the_clouds.config.Config.WorldCloudHeights'!
```

**Comment by DaFuqs** [comment]
Fixed for newest update ✔️
